### PR TITLE
Added a page with some more info, linked to it in half the responses

### PR DESCRIPTION
**Pull request by JohnRoux**

### CODE REVIEW

**Comment by JohnRoux** [comment]
Please note that this is not 100% complete.
For one thing it needs some admin approval and :eyes:
For another we want to add a link for additional information in it. One which helps people evaluate the situation better and not just get triggered

**Comment by n1c** [comment]
This is cool, my only real feedback is I think the opening line sounds a little like "this is only a problem in this group", while it's an overarching social thing that we're just trying to be aware of in the group.

**Comment by zoidyzoidzoid** [comment]
This was replaced by https://github.com/zatech/meta/pull/5, right?

**Comment by JohnRoux** [comment]
Yip, closing :+1:

**Pull request closed without merging**
