### PR TITLE
remove the fluff. get to the point.

### PR DESCRIPTION
**Pull request by sensiblesteve**

### CODE REVIEW

**Comment by sensiblesteve** [comment]
hello, please can someone please review this?

**Comment by JohnRoux** [comment]
Yeah, this would result in WAY more false positive hits imo.
Don't think the swap out of the trigger phrases is worth the cost.

I don't personally mind the response change, but I feel like it is nicer to have it change alternatives

**Comment by n1c** [comment]
Seconded; I don't see any value in this simplification.

**Comment by sensiblesteve** [comment]
1. it's not clear what's "false positive" and what's "positive positive".

some test cases:

"hey guys, who knows what sudo means?" - triggered
"the guys that were building next door" - triggered
"guys, i have news for you" - ok!
"we're looking for some wordpress guys" - ok!
"i need a devops guy" - ok!
"i like guys with blue eyes" - triggered
"hey bros" - ok!
"hi guys and girls" - triggered
"hi boys" - ok!

what would you like to highlight and what would you like to ignore?

2. "gals" is unrelated to "guys" because "gals" is not an ambiguous word that can be used interchangeably with "everyone". its also a very uncommon word, unlike "guys".

**Pull request closed without merging**
